[theme]
# Cor Principal (Botões, Abas, Spinners) - Ciano Sicoob
primaryColor = "#00ae9d"

# Cor de Fundo da Página - Cinza Moderno
backgroundColor = "#f8fafc"

# Cor de Fundo de Elementos Secundários
secondaryBackgroundColor = "#ffffff"

# Cor do Texto
textColor = "#1e293b"

# Fonte Profissional
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
