[theme]
base = "light"
primaryColor = "#00ae9d"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
